import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const readerSource = readFileSync(new URL("./h1-signals.ts", import.meta.url), "utf8");
const redisCoreSource = readFileSync(new URL("./redis-core.ts", import.meta.url), "utf8");
const boardSource = readFileSync(new URL("../components/H1SignalBoard.tsx", import.meta.url), "utf8");
const redesignCss = readFileSync(new URL("../app/oak-redesign.css", import.meta.url), "utf8");
const vipSource = readFileSync(new URL("./vip.ts", import.meta.url), "utf8");
const enginePageSource = readFileSync(new URL("../app/engine/page.tsx", import.meta.url), "utf8");
const historyPageSource = readFileSync(new URL("../app/history/page.tsx", import.meta.url), "utf8");
const evidencePanelSource = readFileSync(new URL("../components/H1EvidencePanel.tsx", import.meta.url), "utf8");
const pngDeliverySource = readFileSync(new URL("./png-delivery.ts", import.meta.url), "utf8");
const rootPageSource = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
const navBarSource = readFileSync(new URL("../components/NavBar.tsx", import.meta.url), "utf8");
const engineBoardSource = readFileSync(new URL("../components/H1EngineBoard.tsx", import.meta.url), "utf8");
const mobileH1RouteSource = readFileSync(new URL("../app/api/mobile/h1/route.ts", import.meta.url), "utf8");
const mobileAppRouteSource = readFileSync(new URL("../app/api/mobile/app/route.ts", import.meta.url), "utf8");
const mobileAppBackendSource = readFileSync(new URL("./mobile-app-backend.ts", import.meta.url), "utf8");
const expoH1Source = readFileSync(new URL("../../../mobile/src/lib/h1.ts", import.meta.url), "utf8");
const expoCalendarSource = readFileSync(new URL("../../../mobile/app/(tabs)/calendar.tsx", import.meta.url), "utf8");
const expoSignalsSource = readFileSync(new URL("../../../mobile/app/(tabs)/signals.tsx", import.meta.url), "utf8");
const androidScreensSource = readFileSync(new URL("../../../android-native/app/src/main/java/uk/oakgatekeeper/mobile/Screens.kt", import.meta.url), "utf8");
const androidModelsSource = readFileSync(new URL("../../../android-native/app/src/main/java/uk/oakgatekeeper/mobile/Models.kt", import.meta.url), "utf8");
const androidStateSource = readFileSync(new URL("../../../android-native/app/src/main/java/uk/oakgatekeeper/mobile/AppState.kt", import.meta.url), "utf8");
const androidMainSource = readFileSync(new URL("../../../android-native/app/src/main/java/uk/oakgatekeeper/mobile/MainActivity.kt", import.meta.url), "utf8");
const androidThemeSource = readFileSync(new URL("../../../android-native/app/src/main/java/uk/oakgatekeeper/mobile/Theme.kt", import.meta.url), "utf8");
const androidShareSource = readFileSync(new URL("../../../android-native/app/src/main/java/uk/oakgatekeeper/mobile/ShareStore.kt", import.meta.url), "utf8");
const androidBuildSource = readFileSync(new URL("../../../android-native/app/build.gradle.kts", import.meta.url), "utf8");
const androidManifestSource = readFileSync(new URL("../../../android-native/app/src/main/AndroidManifest.xml", import.meta.url), "utf8");
const androidStylesSource = readFileSync(new URL("../../../android-native/app/src/main/res/values/styles.xml", import.meta.url), "utf8");
const androidLauncherColorsSource = readFileSync(new URL("../../../android-native/app/src/main/res/values/colors.xml", import.meta.url), "utf8");
const webLoadingSource = readFileSync(new URL("../components/OAKLoadingSplash.tsx", import.meta.url), "utf8");
const brandSyncSource = readFileSync(new URL("../../../tools/sync_brand_assets.py", import.meta.url), "utf8");
const scannerSource = readFileSync(new URL("./h1-cloud-scanner.ts", import.meta.url), "utf8");
const localPatternsSource = readFileSync(new URL("./h1-local-patterns.ts", import.meta.url), "utf8");
const localMarketRouteSource = readFileSync(new URL("../app/api/h1-scanner/local-market/route.ts", import.meta.url), "utf8");
const layoutSource = readFileSync(new URL("../app/layout.tsx", import.meta.url), "utf8");
const manifestSource = readFileSync(new URL("../app/manifest.ts", import.meta.url), "utf8");
const tabAutoRefreshSource = readFileSync(new URL("../components/TabAutoRefresh.tsx", import.meta.url), "utf8");
const nativeH1BoardSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/H1BoardView.swift", import.meta.url), "utf8");
const nativeMainTabSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/MainTabView.swift", import.meta.url), "utf8");
const nativeWorkspaceSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/NativeWorkspaceViews.swift", import.meta.url), "utf8");
const nativeImageTransferSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/ImageTransfer.swift", import.meta.url), "utf8");
const nativeModelsSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/Models.swift", import.meta.url), "utf8");
const nativeSignalsSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/SignalsView.swift", import.meta.url), "utf8");
const nativeEvidenceSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/EvidenceView.swift", import.meta.url), "utf8");
const nativeReportsSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/ReportsView.swift", import.meta.url), "utf8");
const nativeThemeSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/Theme.swift", import.meta.url), "utf8");
const nativeAppStateSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/AppState.swift", import.meta.url), "utf8");
const nativeMoreSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/MoreView.swift", import.meta.url), "utf8");
const nativeAppSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/OAKGatekeeperApp.swift", import.meta.url), "utf8");
const providerAccountStatusSource = readFileSync(new URL("./provider-account-status.ts", import.meta.url), "utf8");
const localPrimaryFenceSource = readFileSync(new URL("./local-primary-fence.ts", import.meta.url), "utf8");
const localControllerSource = readFileSync(new URL("../../../local-failover/oak-local-telegram-failover.mjs", import.meta.url), "utf8");
const licenseSource = readFileSync(new URL("../../../LICENSE", import.meta.url), "utf8");
const localStatusRouteSource = readFileSync(new URL("../app/api/telegram/local-status/route.ts", import.meta.url), "utf8");
const androidGradlePropertiesSource = readFileSync(new URL("../../../android-native/gradle.properties", import.meta.url), "utf8");

test("web keeps one primary H1 navigation surface while legacy History redirects", () => {
  assert.match(navBarSource, /<span>H1 Live<\/span>/);
  assert.doesNotMatch(navBarSource, /href="\/history"/);
  assert.match(historyPageSource, /redirect\("\/engine"\)/);
  assert.doesNotMatch(historyPageSource, /readLatestH1Signals|HistoryClient/);
  assert.match(navBarSource, /<Link href="\/engine" className="oak-brand"/);
  assert.match(navBarSource, /src="\/oak-app-icon\.png(?:\?v=[^"]+)?"/);
  assert.doesNotMatch(navBarSource, /favicon\.ico/);
  assert.match(layoutSource, /icon: "\/oak-app-icon\.png(?:\?v=[^"]+)?"/);
  assert.match(layoutSource, /apple: "\/oak-app-icon\.png(?:\?v=[^"]+)?"/);
  assert.match(layoutSource, /manifest: "\/manifest\.webmanifest"/);
  assert.match(manifestSource, /src: "\/oak-app-icon-192\.png"/);
  assert.match(manifestSource, /src: "\/oak-app-icon-512\.png"/);
  assert.match(rootPageSource, /redirect\("\/engine"\)/);
});

test("H1 web feed schema 18 carries local M15 entry metadata and keeps replica fallback", () => {
  assert.match(readerSource, /H1_SIGNAL_PUBLIC_SCHEMA = 18/);
  assert.match(readerSource, /entryHour/);
  assert.match(readerSource, /patternGroup/);
  assert.match(readerSource, /patternFamily/);
  assert.match(readerSource, /scannerSource/);
  assert.match(readerSource, /inversionBadge/);
  assert.match(readerSource, /sampleBars/);
  assert.match(readerSource, /payload\.schemaVersion !== H1_SIGNAL_PUBLIC_SCHEMA/);
  assert.match(readerSource, /payload\.signalRuleVersion !== H1_SIGNAL_RULE_VERSION/);
  assert.match(readerSource, /readRedisReplicas<unknown>\(LATEST_KEY\)/);
  assert.match(readerSource, /freshestPayload/);
  assert.match(readerSource, /maskFutureH1Signals\(latest\)/);
  assert.match(readerSource, /readRedisReplicas<unknown>\(H1_CLOUD_STATE_KEY\)/);
  assert.match(readerSource, /freshestState/);
  assert.match(readerSource, /buildPublicFeed\(state\)/);
  assert.match(redisCoreSource, /export async function readRedisReplicas/);
  assert.match(redisCoreSource, /Promise\.allSettled/);
});

test("H1 v94 uses five blocks and GBPUSD M15 E-0:15 as the only signal base", () => {
  assert.match(scannerSource, /H1_TARGET_BASES = H1_LOCAL_TARGETS/);
  assert.match(localPatternsSource, /H1_LOCAL_TARGETS = \["XAUUSD"\]/);
  assert.match(localPatternsSource, /H1_SIGNAL_BASE_SOURCES = \["GBPUSD"\]/);
  assert.match(localPatternsSource, /H1_LOCAL_SCAN_HOURS = \[3, 6, 9, 12, 14\]/);
  assert.match(mobileAppBackendSource, /FALLBACK_HOURS = \[3, 6, 9, 12, 14\]/);
  assert.match(mobileAppBackendSource, /FALLBACK_SYMBOLS = \["XAUUSD"\]/);
  assert.match(nativeSignalsSource, /visibleSymbols = \["XAUUSD"\]/);
  assert.match(scannerSource, /H1_SIGNAL_RULE_VERSION = 94/);
  assert.match(scannerSource, /H1_SIGNAL_END_HOUR = 14/);
  assert.match(scannerSource, /includes\(hour\) \? H1_TARGET_BASES : \[\]/);
  assert.match(localMarketRouteSource, /evaluateLocalH1PatternsForTarget/);
  assert.match(scannerSource, /3: \{ baseSymbol: "GBPUSD", inverted: true \}/);
  assert.match(scannerSource, /6: \{ baseSymbol: "GBPUSD", inverted: false \}/);
  assert.match(scannerSource, /9: \{ baseSymbol: "GBPUSD", inverted: false \}/);
  assert.match(scannerSource, /12: \{ baseSymbol: "GBPUSD", inverted: true \}/);
  assert.match(scannerSource, /14: \{ baseSymbol: "GBPUSD", inverted: true \}/);
  assert.doesNotMatch(scannerSource, /16: \{ baseSymbol:/);
  assert.match(scannerSource, /const baseTotalMinutes = entryHour \* 60 - 15/);
  assert.match(scannerSource, /market\[plan\.baseSymbol\]\.bars/);
  assert.match(scannerSource, /bar\.brokerDate === brokerDate && bar\.hour === plan\.baseHour && bar\.minute === plan\.baseMinute/);
  assert.doesNotMatch(scannerSource, /h3EntrySignalDecision|m15SignalBaseForEntry|signalBaseSourceForTarget/);
  assert.match(localPatternsSource, /return "XAUUSD"/);
});

test("web tab softly refreshes server data every 20 seconds", () => {
  assert.match(layoutSource, /<TabAutoRefresh \/>/);
  assert.match(tabAutoRefreshSource, /TAB_AUTO_REFRESH_MS = 20_000/);
  assert.match(tabAutoRefreshSource, /window\.setInterval/);
  assert.match(tabAutoRefreshSource, /router\.refresh\(\)/);
  assert.match(tabAutoRefreshSource, /window\.clearInterval/);
  assert.doesNotMatch(tabAutoRefreshSource, /location\.reload/);
});

test("H16 is retired while Telegram scheduling keeps the existing H14 cutoff", () => {
  assert.match(scannerSource, /H1_SIGNAL_END_HOUR = 14/);
  assert.match(localPatternsSource, /H1_LOCAL_SCAN_HOURS = \[3, 6, 9, 12, 14\]/);
  assert.match(mobileAppBackendSource, /FALLBACK_HOURS = \[3, 6, 9, 12, 14\]/);
  assert.doesNotMatch(scannerSource, /appointmentHour: 22, appointmentMinute: 5/);
  assert.match(scannerSource, /appointmentMinute >= 22 \* 60 \+ 5/);
  assert.doesNotMatch(boardSource, /H16 CLOSE|isManualCloseH16Day/);
  assert.match(boardSource, /H1_SIGNAL_ROWS/);
  assert.doesNotMatch(boardSource + androidScreensSource, /order_send|closePosition|dispatchTask|\/approve/);
});

test("web and native clients expose only shared Entry time plus the XAUUSD v94 signal row", () => {
  assert.match(boardSource, /<b>ENTRY TIME<\/b>/);
  assert.match(boardSource, /entryByHour = new Map\(\(day\?\.symbols\?\.XAUUSD\?\.alerts/);
  assert.match(boardSource, /H1_SIGNAL_ROWS = \["XAUUSD"\]/);
  assert.match(androidScreensSource, /VisibleSymbols = listOf\("XAUUSD"\)/);
  assert.match(nativeH1BoardSource, /visibleSymbols = \["XAUUSD"\]/);
  assert.doesNotMatch(boardSource + androidScreensSource + nativeH1BoardSource, /VisibleSymbols = listOf\("XAUUSD", "GBPUSD"|visibleSymbols = \["XAUUSD", "GBPUSD"|H1_SIGNAL_ROWS = \["XAUUSD", "GBPUSD"/);
  assert.match(scannerSource, /H1_TARGET_BASES = H1_LOCAL_TARGETS/);
});

test("web H1 table renders the final XAU BUY/SELL row directly under shared Entry time", () => {
  assert.match(boardSource, /oak-h1-cell-entry/);
  assert.match(boardSource, /oak-h1-cell-signal oak-h1-cell-evidence/);
  assert.match(boardSource, /signalLabel\(alert\)/);
  assert.match(boardSource, /setEvidenceSelection\(\{ base: symbol/);
  assert.match(boardSource, /BT \+1 · SW \+2/);
  assert.doesNotMatch(boardSource, /previousRetainedBrokerDate|H3 HÔM TRƯỚC|PREV H3/);
  assert.doesNotMatch(boardSource, /data-entry-highlight/);
  assert.match(scannerSource, /highlightedH1BlockHoursForBrokerDate/);
  assert.doesNotMatch(boardSource, /data-block-highlight|highlightedHours/);
  assert.doesNotMatch(redesignCss, /\[data-block-highlight="true"\]/);
  assert.match(scannerSource, /const symbolH1Signal = baseH1Signal/);
  assert.match(scannerSource, /plan\.inverted \? invertSignal\(baseH1Signal\) : baseH1Signal/);
  assert.doesNotMatch(nativeH1BoardSource, /entryReference|isReference\(symbol:/);
  assert.doesNotMatch(androidScreensSource, /entryReference/);
});

test("light theme keeps normal BUY/SELL signal pills high-contrast across every H1 row", () => {
  assert.doesNotMatch(redesignCss, /data-entry-reference|data-manual-close|oak-h1-close-badge/);
  assert.match(redesignCss, /html\.light \.oak-h1-cell-entry small\[data-signal="BUY"\]/);
  assert.match(redesignCss, /html\.light \.oak-h1-cell-entry small\[data-signal="SELL"\]/);
  assert.match(redesignCss, /border-width: 2px/);
});

test("native iOS polish keeps H1 matrix clean, image clipboard, sparse report dates, distinct contrast, and live account toggles", () => {
  const signalCellStart = nativeH1BoardSource.indexOf("private struct H1SignalCell");
  const signalCellEnd = nativeH1BoardSource.indexOf("private struct BrokerCalendarSheet");
  const matrixCellSource = nativeH1BoardSource.slice(signalCellStart, signalCellEnd);
  assert.match(nativeH1BoardSource, /HStack\(alignment: \.top, spacing: 6\)/);
  assert.match(nativeH1BoardSource, /matrixRowLabel\(state\.text\(vn: "GIỜ VÀO", en: "ENTRY TIME"\), compact: true\)/);
  assert.match(nativeH1BoardSource, /H1EntryTimeCell/);
  assert.match(matrixCellSource, /RoundedRectangle\(cornerRadius: 11/);
  assert.doesNotMatch(matrixCellSource, /overlay\(alignment: \.trailing\)|overlay\(alignment: \.bottom\)|Divider\(\)/);

  assert.match(nativeEvidenceSource, /COPY CHART/);
  assert.match(nativeEvidenceSource, /SHARE CHART/);
  assert.match(nativeEvidenceSource, /M15 candlestick chart · oldest → newest/);
  assert.match(nativeEvidenceSource, /private var chronologicalBars:[\s\S]*bars\.sorted/);
  assert.match(androidScreensSource, /val safe = bars\.sortedWith/);
  assert.match(androidShareSource, /val bars = alert\.sampleBars\.sortedWith/);
  assert.match(nativeEvidenceSource, /ImageRenderer\(content: view\)/);
  assert.match(nativeEvidenceSource, /OAKImageTransfer\.copyPNG\(image\)/);
  assert.match(nativeImageTransferSource, /UIPasteboard\.general\.setItems/);
  assert.match(nativeImageTransferSource, /UTType\.png\.identifier/);
  assert.doesNotMatch(nativeEvidenceSource, /public\.svg-image|public\.utf8-plain-text|COPY CHART SVG|<svg/);

  assert.match(nativeReportsSource, /x: \.value\("Index", point\.index\)/);
  assert.match(nativeReportsSource, /AxisMarks\(values: visibleAxisIndices\(reports\.trend\)\)/);
  assert.match(nativeReportsSource, /font\(\.system\(size: 9, weight: \.bold, design: \.monospaced\)\)/);

  assert.match(nativeThemeSource, /case \.contrast: Color\(hex: contrast\)/);
  assert.match(nativeThemeSource, /contrast: 0x000000/);
  assert.match(nativeThemeSource, /contrast: 0xFFFFFF/);
  assert.match(nativeThemeSource, /contrast: 0x66A3FF/);
  assert.match(nativeAppSource, /\.id\(state\.themeMode\)/);

  assert.match(nativeAppStateSource, /applyAccountEnabledLocally\(id: id, enabled: enabled\)/);
  assert.match(nativeAppStateSource, /payload = previous/);
  assert.match(nativeAppStateSource, /Task \{ @MainActor \[weak self\] in/);
  assert.match(nativeMoreSource, /first\(where: \{ \$0\.id == account\.id \}\)\?\.enabled/);
  assert.match(nativeMoreSource, /© 2026 QuachGia/);
  assert.match(nativeMoreSource, /MIT License/);
  assert.match(licenseSource, /MIT License/);
  assert.match(licenseSource, /Copyright \(c\) 2026 QuachGia/);
});

test("mobile account status prefers sanitized local-primary MT5 heartbeat evidence over obsolete cloud bridge status", () => {
  assert.match(localPrimaryFenceSource, /accounts: LocalPrimaryMt5Heartbeat\[\]/);
  assert.match(localControllerSource, /function localPrimaryFenceAccounts/);
  assert.match(localControllerSource, /providerAccountId: String\(row\.providerAccountId/);
  assert.match(localControllerSource, /localReady: row\.localReady !== false/);
  assert.match(localControllerSource, /eaVersion: String\(row\.eaVersion/);
  assert.match(localControllerSource, /const webStatus = options\.webStatus/);
  assert.match(localControllerSource, /\/api\/telegram\/local-status/);
  assert.match(localStatusRouteSource, /x-telegram-bot-api-secret-token/);
  assert.match(localStatusRouteSource, /writeLocalPrimaryFence/);
  assert.match(localStatusRouteSource, /syncManagedMt5AccountsFromLocalHeartbeats/);
  assert.match(localStatusRouteSource, /enabled: row\.enabled !== false/);
  assert.match(localStatusRouteSource, /MAX_CLOCK_SKEW_MS/);
  assert.match(androidScreensSource, /© 2026 QuachGia/);
  assert.match(androidScreensSource, /local heartbeat online/);
  assert.match(androidScreensSource, /Local heartbeat pending/);
  assert.match(androidManifestSource, /android:icon="@mipmap\/ic_launcher"/);
  const androidAdaptiveIconSource = readFileSync(new URL("../../../android-native/app/src/main/res/mipmap-anydpi/ic_launcher.xml", import.meta.url), "utf8");
  assert.match(androidAdaptiveIconSource, /@color\/oak_launcher_mask_bg/);
  assert.match(androidAdaptiveIconSource, /@drawable\/oak_launcher_foreground/);
  assert.doesNotMatch(androidAdaptiveIconSource, /oak_launcher_foreground_inset/);
  assert.match(androidAdaptiveIconSource, /@drawable\/oak_launcher_monochrome/);
  assert.match(androidLauncherColorsSource, /<color name="oak_launcher_bg">#07110F<\/color>/);
  assert.match(androidLauncherColorsSource, /<color name="oak_launcher_mask_bg">#07110F<\/color>/);
  const nativeProjectSource = readFileSync(new URL("../../../ios-native/project.yml", import.meta.url), "utf8");
  const nativeAppIconCatalogSource = readFileSync(new URL("../../../ios-native/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json", import.meta.url), "utf8");
  assert.match(nativeProjectSource, /ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon/);
  assert.match(nativeProjectSource, /path: Resources[\s\S]*buildPhase: resources/);
  assert.match(nativeAppIconCatalogSource, /"filename" : "AppIcon\.png"/);
  assert.match(nativeAppIconCatalogSource, /"size" : "1024x1024"/);
  assert.match(providerAccountStatusSource, /readLocalPrimaryFence/);
  assert.match(providerAccountStatusSource, /bridgeRuntime: "local-primary"/);
  assert.match(providerAccountStatusSource, /local-primary-offline/);
  assert.match(providerAccountStatusSource, /Boolean\(account\.bridgeProfile\) && sameText\(row\.profile, account\.bridgeProfile\)/);
  assert.match(providerAccountStatusSource, /const bridgeRuntime: "local-primary-offline" \| "local-primary-pending"/);
  assert.match(providerAccountStatusSource, /getMt5BridgeHeartbeat/);
  assert.match(mobileAppBackendSource, /providerAccountsWithRuntimeStatus\(accounts\)/);
  assert.match(nativeMoreSource, /Local heartbeat online/);
  assert.match(nativeMoreSource, /Local heartbeat offline/);
  assert.match(androidScreensSource, /Local heartbeat offline/);
  assert.doesNotMatch(nativeMoreSource, /Bridge offline|bridge online/);
});

test("H1 table sizes itself from the active columns and stretches across desktop viewports", () => {
  assert.match(redesignCss, /\.oak-engine-screen \{[^}]*width: 100%;/);
  assert.match(redesignCss, /\.oak-h1-table \{[^}]*width: max-content;[^}]*min-width: 100%;/);
  assert.match(redesignCss, /\.oak-h1-table th, \.oak-h1-table td \{[^}]*min-width: 4\.45rem;/);
  assert.match(redesignCss, /@media \(min-width: 900px\) \{[\s\S]*?\.oak-h1-table \{ width: 100%; min-width: 100%; \}[\s\S]*?\.oak-h1-table th, \.oak-h1-table td \{ width: auto; min-width: 0; \}/);
  assert.match(redesignCss, /\.oak-h1-symbol-sticky \{ width: clamp\(8rem, 10vw, 11rem\) !important;/);
  assert.doesNotMatch(redesignCss, /\.oak-engine-screen \{[^}]*1080px/);
  assert.doesNotMatch(redesignCss, /\.oak-h1-table \{[^}]*min-width: 79rem;/);
});

test("H1 board omits the separate Entry Focus panel", () => {
  assert.doesNotMatch(boardSource, /H1EntryFocus|oak-entry-focus/);
  assert.match(boardSource, /oak-h1-history/);
  assert.match(boardSource, /oak-h1-table/);
  assert.doesNotMatch(redesignCss, /\.oak-entry-focus/);
});

test("unified H1 web surface temporarily exposes every entry cell as free access", () => {
  assert.match(vipSource, /VIP_FREE_ACCESS = true/);
  assert.match(boardSource, /FREE ACCESS/);
  assert.match(boardSource, /All H1 entry-time cells unlocked/);
  assert.match(boardSource, /oak-access-pill/);
  assert.doesNotMatch(boardSource, /VIP_SIGNAL_SYMBOL|oak-h1-cell-locked|VIP required/);
  assert.doesNotMatch(engineBoardSource, /VIP UNLOCK|VIP LOCKED|\/api\/vip|useDialogFocusTrap/);
  assert.doesNotMatch(enginePageSource, /redactH1Signals|getVipAccessState/);
  assert.doesNotMatch(historyPageSource, /redactH1Signals|getVipAccessState/);
});

test("unified H1 uses a deterministic Sunday-first history calendar without weekday filter controls", () => {
  assert.match(boardSource, /function SundayCalendarPicker/);
  assert.match(boardSource, /\[\"CN\", \"T2\", \"T3\", \"T4\", \"T5\", \"T6\", \"T7\"\]/);
  assert.match(boardSource, /getUTCDay\(\)/);
  assert.match(boardSource, /sundayOffset/);
  assert.match(boardSource, /allowedDates=\{allDates\}/);
  assert.match(boardSource, /disabled=\{!allDates\.length\}/);
  assert.match(boardSource, /data-empty=\"true\"/);
  assert.match(boardSource, /fallbackMinDate/);
  assert.match(boardSource, /calendar dự phòng/);
  assert.doesNotMatch(boardSource, /type=\"date\"/);
  assert.doesNotMatch(boardSource, /HISTORY_FILTERS|weekdayFilter|oak-h1-history-options|Lọc theo thứ|Filter by weekday/);
  assert.match(redesignCss, /\.oak-h1-calendar-picker \{/);
  assert.match(redesignCss, /\.oak-h1-calendar-weekdays/);
  assert.match(redesignCss, /grid-template-columns: repeat\(7, 1\.75rem\)/);
  assert.match(redesignCss, /width: min\(15rem, calc\(100vw - 1\.25rem\)\)/);
  assert.match(redesignCss, /\.oak-h1-board \{[\s\S]*?overflow: visible;/);
  assert.match(redesignCss, /\.oak-h1-history \{[^}]*z-index: 30;[^}]*overflow: visible;/);
  assert.match(redesignCss, /\.oak-h1-table-scroll \{[^}]*overflow-y: hidden;[^}]*border-radius:/);
  assert.doesNotMatch(redesignCss, /\.oak-h1-board \{[^}]*overflow: hidden;/);
  assert.doesNotMatch(redesignCss, /width: min\(20\.5rem/);
  assert.doesNotMatch(boardSource, /oak-h1-history-dates/);
});

test("legacy weekday/CẦU/H3-selector presentation stays hidden while v94 GBPUSD M15 evidence is explicit", () => {
  assert.doesNotMatch(boardSource, /inversionBadge|data-post-signal-inverted|ĐẢO/);
  assert.doesNotMatch(boardSource, /isMonthEndBridgeCell|oak-h1-bridge-badge|data-month-end-bridge|CẦU/);
  assert.doesNotMatch(evidencePanelSource, /Weekday:|WEEKDAY|ĐẢO|GIỮ|h3-prev-|h3-today-|H3 ENTRY/);
  assert.match(evidencePanelSource, /M15 BASE ·/);
  assert.match(evidencePanelSource, /ENTRY-BLOCK/);
  assert.match(evidencePanelSource, /E-0:15/);
  assert.match(evidencePanelSource, /SIGNAL/);
  assert.match(evidencePanelSource, /BASE CANDLE/);
});

test("mobile H1 adapter preserves admin auth and normalized cloud feed semantics", () => {
  assert.match(mobileH1RouteSource, /requireAdminOrApiAuth/);
  assert.match(mobileH1RouteSource, /getLatestH1Signals/);
  assert.match(mobileH1RouteSource, /maskFutureH1Signals/);
  assert.match(mobileH1RouteSource, /Cache-Control.*no-store/);
  assert.doesNotMatch(mobileH1RouteSource, /UPSTASH|CTRADER_CLIENT_SECRET|DASHBOARD_API_KEY/);
});

test("mobile app backend exposes one authenticated app payload without leaking secrets", () => {
  assert.match(mobileAppRouteSource, /requireAdminOrApiAuth/);
  assert.match(mobileAppRouteSource, /buildMobileAppPayload/);
  assert.match(mobileAppRouteSource, /Cache-Control.*no-store/);
  assert.match(mobileAppBackendSource, /dashboardSummary/);
  assert.match(mobileAppBackendSource, /reportSummary/);
  assert.match(mobileAppBackendSource, /bridgeSummary/);
  assert.match(mobileAppBackendSource, /systemSummary/);
  assert.match(mobileAppBackendSource, /payloadVersion: 2/);
  assert.match(mobileAppBackendSource, /isMonthEndBridgeCell/);
  assert.doesNotMatch(mobileAppRouteSource + mobileAppBackendSource, /CTRADER_CLIENT_SECRET|DASHBOARD_API_KEY|UPSTASH_REDIS_REST_TOKEN/);
});

test("native iOS and Android mirror the web three-tab hierarchy with animated H1 geometry", () => {
  assert.match(nativeMainTabSource, /AppState\.Tab\.live/);
  assert.match(nativeMainTabSource, /AppState\.Tab\.neotech/);
  assert.match(nativeMainTabSource, /AppState\.Tab\.tools/);
  assert.doesNotMatch(nativeMainTabSource, /AppState\.Tab\.history|AppState\.Tab\.signals|AppState\.Tab\.reports|AppState\.Tab\.more/);
  assert.match(nativeH1BoardSource, /H1NativeCommandHero/);
  assert.match(nativeH1BoardSource, /OAKNativeOrbitCore/);
  assert.match(nativeH1BoardSource, /TimelineView\(\.animation/);
  assert.match(nativeH1BoardSource, /rotation3DEffect/);
  assert.match(nativeWorkspaceSource, /struct NeoTechNativeView/);
  assert.match(nativeWorkspaceSource, /struct NativeToolsView/);
  assert.match(nativeAppStateSource, /enum ToolsRoute: Hashable, Sendable/);
  assert.match(nativeAppStateSource, /var toolsPath: \[ToolsRoute\] = \[\]/);
  assert.match(nativeMainTabSource, /NavigationStack\(path: \$state\.toolsPath\)/);
  assert.match(nativeWorkspaceSource, /route: AppState\.ToolsRoute\.system/);
  assert.match(nativeWorkspaceSource, /NavigationLink\(value: route\)/);

  assert.match(androidMainSource, /OAKTab\.LIVE/);
  assert.match(androidMainSource, /OAKTab\.NEOTECH/);
  assert.match(androidMainSource, /OAKTab\.TOOLS/);
  assert.doesNotMatch(androidMainSource, /OAKTab\.HISTORY|OAKTab\.SIGNALS|OAKTab\.REPORTS|OAKTab\.MORE/);
  assert.match(androidMainSource, /NavigationBarItem/);
  assert.match(androidScreensSource, /fun H1BoardScreen\(state: OAKAppState\)/);
  assert.match(androidScreensSource, /H1CommandHero/);
  assert.match(androidScreensSource, /OAKOrbitCore/);
  assert.match(androidScreensSource, /rememberInfiniteTransition/);
  assert.match(androidScreensSource, /orbit-vertical/);
  assert.match(androidScreensSource, /rotationY = 72f; rotationX = vertical/);
  assert.match(androidScreensSource, /fun NeoTechScreen/);
  assert.match(androidScreensSource, /fun ToolsScreen/);
  assert.match(androidScreensSource, /BackHandler\(enabled = panel != NativeToolPanel\.DIRECTORY\)/);
  assert.doesNotMatch(androidScreensSource + androidMainSource, /VIP UNLOCKED|HỆ THỐNG ONLINE|DashboardScreen|OAK SLTP/);
});

test("native Android copies the iOS H1 presentation, evidence, reports, themes and account interaction", () => {
  assert.match(androidScreensSource, /VisibleSymbols = listOf\("XAUUSD"\)/);
  assert.doesNotMatch(androidScreensSource, /entryReference/);
  assert.match(androidScreensSource, /OAKPill\("FREE ACCESS", PillTone\.SUCCESS\)/);
  assert.match(androidScreensSource, /BrokerCalendarSheet/);
  assert.match(androidScreensSource, /listOf\("CN", "T2", "T3", "T4", "T5", "T6", "T7"\)/);
  assert.match(androidScreensSource, /List\(42\)/);
  assert.match(androidScreensSource, /monthAnchor\.minusMonths\(1\)/);
  assert.match(androidScreensSource, /monthAnchor\.plusMonths\(1\)/);
  assert.match(androidScreensSource, /Icons\.Default\.DateRange/);
  assert.match(androidScreensSource, /COPY PNG/);
  assert.match(androidScreensSource, /SHARE PNG/);
  assert.match(androidScreensSource, /COPY CHART/);
  assert.match(androidScreensSource, /SHARE CHART/);
  assert.match(androidShareSource, /copyScheduleToClipboard/);
  assert.match(androidShareSource, /Intent\.ACTION_SEND/);
  assert.match(androidShareSource, /Intent\.EXTRA_STREAM/);
  assert.match(androidShareSource, /Intent\.FLAG_GRANT_READ_URI_PERMISSION/);
  assert.match(androidShareSource, /Intent\.createChooser/);
  assert.match(androidShareSource, /ClipData\.newUri/);
  assert.match(androidShareSource, /createBitmap\(Width, Height/);
  assert.match(androidShareSource, /bitmap\.recycle\(\)/);
  assert.match(androidScreensSource, /bar\.brokerTime/);
  assert.match(androidScreensSource, /index == 0 \|\| index == trend\.lastIndex \|\| index % 2 == 0/);
  assert.match(androidThemeSource, /canvas = Color\.Black/);
  assert.match(androidThemeSource, /text = Color\.White/);
  assert.match(androidStateSource, /applyAccountEnabledLocally\(id, enabled\)/);
  assert.match(androidStateSource, /payload = previous/);
  assert.match(androidStateSource, /fun unlock\(candidate: String\)/);
  assert.match(androidStateSource, /viewModelScope\.launch/);
  assert.match(androidStateSource, /val initialPayload = api\.fetchApp\(key\)/);
  assert.doesNotMatch(androidScreensSource, /rememberCoroutineScope/);
  assert.doesNotMatch(androidStateSource, /refresh\(forceLoading = true\)/);
  assert.match(androidScreensSource, /Switch\(\s*checked = account\.enabled,/);
  assert.match(androidScreensSource, /© 2026 QuachGia/);
  assert.match(androidScreensSource, /MIT License/);
  assert.match(androidMainSource, /R\.drawable\.ic_tab_live/);
  assert.match(androidMainSource, /R\.drawable\.ic_tab_signals/);
  assert.match(androidMainSource, /R\.drawable\.ic_tab_more/);
});

test("native Android is hardened for Google Play February 2027 memory and DEX requirements", () => {
  assert.match(androidBuildSource, /compileSdk = 36/);
  assert.match(androidBuildSource, /targetSdk = 36/);
  assert.match(androidBuildSource, /isMinifyEnabled = true/);
  assert.match(androidBuildSource, /isShrinkResources = true/);
  assert.match(androidBuildSource, /warningsAsErrors = true/);
  assert.match(androidBuildSource, /"OldTargetApi", "AndroidGradlePluginVersion", "GradleDependency"/);
  assert.match(androidBuildSource, /jniLibs\.useLegacyPackaging = false/);
  assert.match(androidGradlePropertiesSource, /android\.enableR8\.fullMode=true/);
  assert.match(androidMainSource, /onTrimMemory/);
  assert.match(androidMainSource, /TRIM_MEMORY_UI_HIDDEN/);
  assert.match(androidMainSource, /onLowMemory/);
  assert.match(androidShareSource, /trimTransient/);
  assert.match(androidShareSource, /ExportRetentionMs/);
  assert.match(androidShareSource, /ClipboardSafetyWindowMs/);
  assert.match(androidShareSource, /pruneExports\(context\)/);
  assert.doesNotMatch(androidShareSource, /listFiles\(\)\?\.forEach \{ it\.delete\(\) \}/);
  assert.doesNotMatch(androidScreensSource + androidStateSource, /Coil|Glide|BitmapFactory|staticBitmap|imageCache/i);
  assert.match(androidManifestSource, /android:allowBackup="false"/);
  assert.match(androidManifestSource, /android:fullBackupContent="false"/);
  assert.match(androidManifestSource, /android:dataExtractionRules="@xml\/data_extraction_rules"/);
  assert.match(androidManifestSource, /Theme\.OAKGatekeeper\.Splash/);
  assert.match(androidStylesSource, /parent="Theme\.SplashScreen"/);
  assert.match(androidStylesSource, /windowSplashScreenAnimatedIcon/);
  assert.match(androidMainSource, /installSplashScreen\(\)/);
  assert.match(androidMainSource, /OAKLaunchLoading/);
  assert.match(androidMainSource, /OAKOrbitCore\(Modifier\.size\(118\.dp\), label = "OAK"\)/);
  assert.match(nativeAppSource, /OAKLaunchLoadingView/);
  assert.match(nativeAppSource, /OAKNativeOrbitCore\(label: "OAK"\)/);
  assert.match(webLoadingSource, /OrbitBrandMark label="OAK"/);
  assert.doesNotMatch(webLoadingSource, /oak-app-icon\.png|oak-loading-spinner|ProgressView|CircularProgressIndicator/);
  assert.match(brandSyncSource, /render_orbit_icon/);
  assert.match(brandSyncSource, /AppIcon\.appiconset/);
  assert.match(brandSyncSource, /oak_launcher_foreground\.png/);
  assert.match(brandSyncSource, /oak_launcher_monochrome\.png/);
  assert.match(brandSyncSource, /oak-app-icon\.png/);
  assert.doesNotMatch(androidManifestSource, /android:screenOrientation="portrait"/);
});

test("engine web surface is local-H1-only with the compact command header", () => {
  assert.doesNotMatch(enginePageSource, /getLatestPattern5|filterActivePattern5|maskFuturePattern5|redactPattern5Signals/);
  assert.doesNotMatch(engineBoardSource, /Pattern5Payload|Pattern5Table|ENGINE 05|Pattern Matrix|Trạng thái tín hiệu hiện tại|<small>PROFILE<\/small>|h1Data\?\.profile/);
  assert.match(engineBoardSource, /<EngineCore data=\{h1Data\}/);
  assert.doesNotMatch(engineBoardSource, /mode="live"|mode="history"/);
  assert.match(boardSource, /MT5 ICMarkets · M15/);
  assert.doesNotMatch(engineBoardSource, /UNLOCK SIGNALS/);
});

test("H1 board exports interoperable PNG with clipboard, Android share-sheet and download fallbacks", () => {
  assert.match(boardSource, /oak-h1-share-png/);
  assert.match(boardSource, /document\.createElement\("canvas"\)/);
  assert.match(boardSource, /canvas\.toBlob/);
  assert.match(boardSource, /H1_SHARE_SCALE = 2/);
  assert.match(boardSource, /H1_SHARE_SYMBOL_WIDTH = 148/);
  assert.match(boardSource, /H1_SHARE_HOUR_WIDTH = 96/);
  assert.match(boardSource, /GBPUSD M15 base E-0:15/);
  assert.match(boardSource, /H3 invert/);
  assert.match(boardSource, /H6\/H9 keep/);
  assert.match(boardSource, /H12\/H14 invert/);
  assert.match(boardSource, /Base GBPUSD M15 E-0:15/);
  assert.doesNotMatch(boardSource, /H16 GU keep|H1 base: H3 AU keep/);
  assert.match(boardSource, /deliverPngBlob/);
  assert.match(boardSource, /SHARED/);
  assert.match(boardSource, /SAVED/);
  assert.match(pngDeliverySource, /navigator\.clipboard\?\.write/);
  assert.match(pngDeliverySource, /new ClipboardItem\(\{ "image\/png": blob \}\)/);
  assert.match(pngDeliverySource, /navigator\.share/);
  assert.match(pngDeliverySource, /navigator\.canShare/);
  assert.match(pngDeliverySource, /anchor\.download = options\.fileName/);
  assert.match(pngDeliverySource, /AbortError/);
  assert.match(nativeH1BoardSource, /copySchedulePNG/);
  assert.match(nativeH1BoardSource, /shareSchedulePNG/);
  assert.match(nativeH1BoardSource, /private struct ScheduleExportMatrix/);
  assert.match(nativeH1BoardSource, /ScheduleExportMatrix\(h1: h1, date: date, symbols: symbols\)/);
  assert.match(nativeH1BoardSource, /ForEach\(h1\.hours, id: \\.self\)/);
  assert.match(nativeH1BoardSource, /h1\.alert\(date: date, symbol: symbol, hour: hour\)/);
  const nativeExportStart = nativeH1BoardSource.indexOf("private struct ScheduleExportView");
  const nativeExportSource = nativeH1BoardSource.slice(nativeExportStart);
  assert.doesNotMatch(nativeExportSource, /H1MatrixView\(/);
  assert.doesNotMatch(nativeExportSource, /ScrollView\(\.horizontal/);
  assert.match(androidShareSource, /val hours = h1\.hours/);
  assert.match(androidShareSource, /val alert = h1\.alert\(brokerDate, symbol, hour\)/);
  assert.match(nativeH1BoardSource, /OAKImageTransfer\.copyPNG\(image\)/);
  assert.match(nativeH1BoardSource, /OAKImageTransfer\.exportPNG/);
  assert.match(nativeH1BoardSource, /SHARE PNG/);
  assert.match(nativeImageTransferSource, /UTType\.png\.identifier/);
  assert.match(nativeImageTransferSource, /UIPasteboard\.general\.setItems/);
  assert.match(nativeImageTransferSource, /\.localOnly: false/);
  assert.match(nativeImageTransferSource, /UIActivityViewController/);
  assert.match(nativeImageTransferSource, /retentionSeconds/);
  assert.match(nativeEvidenceSource, /SHARE CHART/);
  assert.match(nativeEvidenceSource, /OAKImageTransfer\.copyPNG\(image\)/);
  assert.match(androidShareSource, /copyScheduleToClipboard/);
  assert.match(androidShareSource, /shareSchedule/);
  assert.match(androidShareSource, /shareChart/);
  assert.match(androidShareSource, /clipboard\.setPrimaryClip\(clip\)/);
  assert.match(androidShareSource, /type = "image\/png"/);
  assert.match(androidScreensSource, /Đã copy PNG · có thể dán sang Telegram/);
  assert.match(boardSource, /activeH1ScanHoursForBrokerDate\(date, data\.hours\)/);
  assert.match(boardSource, /hours\.forEach/);
  assert.match(boardSource, /entryHourLabel\(entryByHour\.get\(hour\)\)/);
  assert.match(boardSource, /H1_SIGNAL_ROWS\.forEach/);
  assert.match(boardSource, /signalAlertForHour\(day, symbol, hour\)/);
  assert.doesNotMatch(boardSource, /const previousReference =|data-entry-highlight/);
  assert.doesNotMatch(boardSource, /highlightBg|highlightedHours\.has\(hour\)|data-block-highlight/);
  assert.match(redesignCss, /\.oak-h1-share-png \{/);
  assert.match(redesignCss, /data-copied="true"/);
});

test("populated H1 cells expose synchronized XAU entry-pattern plus GBPUSD M15 signal evidence", () => {
  assert.match(boardSource, /oak-h1-cell-entry oak-h1-cell-evidence/);
  assert.match(boardSource, /oak-h1-cell-signal oak-h1-cell-evidence/);
  assert.match(boardSource, /setEvidenceSelection/);
  assert.match(boardSource, /<H1EvidencePanel variant="inline" selection=\{evidenceSelection\} payload=\{data\}/);
  assert.match(evidencePanelSource, /function evidenceFacts\(/);
  assert.match(evidencePanelSource, /BASE CANDLE/);
  assert.match(evidencePanelSource, /BASE OHLC/);
  assert.match(evidencePanelSource, /SIGNAL SOURCE/);
  assert.match(evidencePanelSource, /signalBaseBar/);
  assert.match(evidencePanelSource, /M15 BASE ·/);
  assert.match(evidencePanelSource, /ENTRY-BLOCK/);
  assert.match(evidencePanelSource, /INVERT/);
  assert.match(evidencePanelSource, /KEEP/);
  assert.match(nativeModelsSource, /M15 BASE ·/);
  assert.match(androidModelsSource, /M15 BASE ·/);
  assert.match(nativeModelsSource, /ENTRY-BLOCK/);
  assert.match(nativeModelsSource, /postSignalInverted \?\? false/);
  assert.match(androidModelsSource, /ENTRY-BLOCK/);
  assert.doesNotMatch(nativeModelsSource + androidModelsSource, /M15 entry-2h15|sourceAlert\.symbol == "USDCAD"|sourceAlert\.symbol == "USDJPY"/);
  assert.match(evidencePanelSource, /M15 candlestick pattern evidence/);
  assert.match(evidencePanelSource, /ENTRY PATTERN · M15/);
  assert.match(evidencePanelSource, /sampleBars/);
  assert.match(evidencePanelSource, /Pattern Evidence · newest → oldest/);
  assert.match(evidencePanelSource, /copy: "Copy chart"/);
  assert.match(evidencePanelSource, /renderEvidenceChartPng/);
  assert.match(evidencePanelSource, /renderEvidenceChartPng\(svg, selection, payload\)/);
  assert.match(evidencePanelSource, /ENTRY PATTERN \$\{patternSource\}/);
  assert.match(evidencePanelSource, /PLOT OLDEST→NEWEST/);
  assert.match(evidencePanelSource, /MATCH READ NEWEST→OLDEST/);
  assert.match(evidencePanelSource, /SIGNAL BASE \$\{selection\.alert\.baseSymbol \|\| selection\.base\} M15/);
  assert.match(evidencePanelSource, /blockBaseRuleLabel\(selection\)/);
  assert.match(evidencePanelSource, /BASE OHLC \$\{facts\.baseOhlc\}/);
  assert.match(evidencePanelSource, /deliverPngBlob/);
  assert.match(evidencePanelSource, /delivery === "shared"/);
  assert.match(evidencePanelSource, /delivery === "downloaded"/);
  assert.match(evidencePanelSource, /canvas\.toBlob/);
  assert.match(evidencePanelSource, /BLOCK H/);
  assert.match(evidencePanelSource, /ENTRY H/);
  assert.match(evidencePanelSource, /familyLabel/);
  assert.match(redesignCss, /\.oak-h1-evidence-panel/);
  assert.match(redesignCss, /\.oak-h1-evidence-chart/);
  assert.match(boardSource, /base: "XAUUSD"/);
  assert.match(boardSource, /setEvidenceSelection\(\{ base: symbol/);
});
