import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const readerSource = readFileSync(new URL("./h1-signals.ts", import.meta.url), "utf8");
const redisCoreSource = readFileSync(new URL("./redis-core.ts", import.meta.url), "utf8");
const boardSource = readFileSync(new URL("../components/H1SignalBoard.tsx", import.meta.url), "utf8");
const redesignCss = readFileSync(new URL("../app/oak-redesign.css", import.meta.url), "utf8");
const vipSource = readFileSync(new URL("./vip.ts", import.meta.url), "utf8");
const enginePageSource = readFileSync(new URL("../app/engine/page.tsx", import.meta.url), "utf8");
const historyPageSource = readFileSync(new URL("../app/history/page.tsx", import.meta.url), "utf8");
const evidencePanelSource = readFileSync(new URL("../components/H1EvidencePanel.tsx", import.meta.url), "utf8");
const rootPageSource = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
const navBarSource = readFileSync(new URL("../components/NavBar.tsx", import.meta.url), "utf8");
const engineBoardSource = readFileSync(new URL("../components/H1EngineBoard.tsx", import.meta.url), "utf8");
const mobileH1RouteSource = readFileSync(new URL("../app/api/mobile/h1/route.ts", import.meta.url), "utf8");
const mobileAppRouteSource = readFileSync(new URL("../app/api/mobile/app/route.ts", import.meta.url), "utf8");
const mobileAppBackendSource = readFileSync(new URL("./mobile-app-backend.ts", import.meta.url), "utf8");
const androidScreensSource = readFileSync(new URL("../../../android-native/app/src/main/java/uk/oakgatekeeper/mobile/Screens.kt", import.meta.url), "utf8");
const androidModelsSource = readFileSync(new URL("../../../android-native/app/src/main/java/uk/oakgatekeeper/mobile/Models.kt", import.meta.url), "utf8");
const androidStateSource = readFileSync(new URL("../../../android-native/app/src/main/java/uk/oakgatekeeper/mobile/AppState.kt", import.meta.url), "utf8");
const androidMainSource = readFileSync(new URL("../../../android-native/app/src/main/java/uk/oakgatekeeper/mobile/MainActivity.kt", import.meta.url), "utf8");
const androidThemeSource = readFileSync(new URL("../../../android-native/app/src/main/java/uk/oakgatekeeper/mobile/Theme.kt", import.meta.url), "utf8");
const androidShareSource = readFileSync(new URL("../../../android-native/app/src/main/java/uk/oakgatekeeper/mobile/ShareStore.kt", import.meta.url), "utf8");
const androidBuildSource = readFileSync(new URL("../../../android-native/app/build.gradle.kts", import.meta.url), "utf8");
const androidManifestSource = readFileSync(new URL("../../../android-native/app/src/main/AndroidManifest.xml", import.meta.url), "utf8");
const androidStylesSource = readFileSync(new URL("../../../android-native/app/src/main/res/values/styles.xml", import.meta.url), "utf8");
const androidLauncherColorsSource = readFileSync(new URL("../../../android-native/app/src/main/res/values/colors.xml", import.meta.url), "utf8");
const webLoadingSource = readFileSync(new URL("../components/OAKLoadingSplash.tsx", import.meta.url), "utf8");
const brandSyncSource = readFileSync(new URL("../../../tools/sync_brand_assets.py", import.meta.url), "utf8");
const scannerSource = readFileSync(new URL("./h1-cloud-scanner.ts", import.meta.url), "utf8");
const localPatternsSource = readFileSync(new URL("./h1-local-patterns.ts", import.meta.url), "utf8");
const localMarketRouteSource = readFileSync(new URL("../app/api/h1-scanner/local-market/route.ts", import.meta.url), "utf8");
const layoutSource = readFileSync(new URL("../app/layout.tsx", import.meta.url), "utf8");
const tabAutoRefreshSource = readFileSync(new URL("../components/TabAutoRefresh.tsx", import.meta.url), "utf8");
const nativeH1BoardSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/H1BoardView.swift", import.meta.url), "utf8");
const nativeImageTransferSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/ImageTransfer.swift", import.meta.url), "utf8");
const nativeModelsSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/Models.swift", import.meta.url), "utf8");
const nativeSignalsSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/SignalsView.swift", import.meta.url), "utf8");
const nativeEvidenceSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/EvidenceView.swift", import.meta.url), "utf8");
const nativeReportsSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/ReportsView.swift", import.meta.url), "utf8");
const nativeThemeSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/Theme.swift", import.meta.url), "utf8");
const nativeAppStateSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/AppState.swift", import.meta.url), "utf8");
const nativeMoreSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/MoreView.swift", import.meta.url), "utf8");
const nativeAppSource = readFileSync(new URL("../../../ios-native/Sources/OAKGatekeeper/OAKGatekeeperApp.swift", import.meta.url), "utf8");
const providerAccountStatusSource = readFileSync(new URL("./provider-account-status.ts", import.meta.url), "utf8");
const localPrimaryFenceSource = readFileSync(new URL("./local-primary-fence.ts", import.meta.url), "utf8");
const localControllerSource = readFileSync(new URL("../../../local-failover/oak-local-telegram-failover.mjs", import.meta.url), "utf8");
const licenseSource = readFileSync(new URL("../../../LICENSE", import.meta.url), "utf8");
const localStatusRouteSource = readFileSync(new URL("../app/api/telegram/local-status/route.ts", import.meta.url), "utf8");
const androidGradlePropertiesSource = readFileSync(new URL("../../../android-native/gradle.properties", import.meta.url), "utf8");

test("H1 Live and web History are reopened as primary trading navigation", () => {
  assert.match(navBarSource, /<span>H1 Live<\/span>/);
  assert.match(navBarSource, /href="\/history"/);
  assert.match(navBarSource, /<Link href="\/engine" className="oak-brand"/);
  assert.match(rootPageSource, /redirect\("\/engine"\)/);
});

test("H1 web feed schema 18 carries local M15 entry metadata and keeps replica fallback", () => {
  assert.match(readerSource, /H1_SIGNAL_PUBLIC_SCHEMA = 18/);
  assert.match(readerSource, /entryHour/);
  assert.match(readerSource, /patternGroup/);
  assert.match(readerSource, /patternFamily/);
  assert.match(readerSource, /scannerSource/);
  assert.match(readerSource, /inversionBadge/);
  assert.match(readerSource, /sampleBars/);
  assert.match(readerSource, /payload\.schemaVersion !== H1_SIGNAL_PUBLIC_SCHEMA/);
  assert.match(readerSource, /payload\.signalRuleVersion !== H1_SIGNAL_RULE_VERSION/);
  assert.match(readerSource, /readRedisReplicas<unknown>\(LATEST_KEY\)/);
  assert.match(readerSource, /freshestPayload/);
  assert.match(readerSource, /maskFutureH1Signals\(latest\)/);
  assert.match(readerSource, /readRedisReplicas<unknown>\(H1_CLOUD_STATE_KEY\)/);
  assert.match(readerSource, /freshestState/);
  assert.match(readerSource, /buildPublicFeed\(state\)/);
  assert.match(redisCoreSource, /export async function readRedisReplicas/);
  assert.match(redisCoreSource, /Promise\.allSettled/);
});

test("H1 rows and block set match the local ICMarkets v74 contract", () => {
  assert.match(scannerSource, /H1_TARGET_BASES = H1_LOCAL_TARGETS/);
  assert.match(localPatternsSource, /H1_LOCAL_TARGETS = \["XAUUSD", "GBPUSD", "EURUSD", "GBPAUD", "GBPCAD", "GBPJPY"\]/);
  assert.match(localPatternsSource, /H1_LOCAL_SCAN_HOURS = \[3, 6, 9, 12, 14, 16\]/);
  assert.match(scannerSource, /if \(hour === 3\) return \["XAUUSD", "GBPAUD"\]/);
  assert.match(scannerSource, /if \(hour === 6\) return \["XAUUSD", "GBPAUD", "GBPJPY"\]/);
  assert.match(localMarketRouteSource, /evaluateLocalH1PatternsForTarget/);
  assert.match(scannerSource, /xauH3EntryHour/);
  assert.doesNotMatch(scannerSource, /manualCloseOnly|closeH16FromXauH5/);
  assert.doesNotMatch(scannerSource, /symbolH1Signal = manualCloseOnly \? null : derivedSignal/);
  assert.doesNotMatch(scannerSource, /weekdaySyncSignalInverted/);
  assert.match(scannerSource, /const derivedSignal = syncToXau \? xauSignal : baseH1Signal/);
  assert.match(scannerSource, /if \(slotHour === 16\)/);
  assert.match(scannerSource, /evaluateLocalH1PatternsForTarget\(base, brokerDate, market, \[14\], 14\)/);
  assert.match(scannerSource, /h3EntryHour === 4 && h14Signal \? invertSignal\(h14Signal\) : h14Signal/);
  assert.match(scannerSource, /base === "GBPUSD"/);
  assert.match(scannerSource, /base === "EURUSD"/);
  assert.match(scannerSource, /patternDriverTargetFor/);
  assert.match(scannerSource, /entryDriverTargetFor/);
  assert.match(scannerSource, /base === "GBPUSD" \|\| base === "EURUSD"[^\n]*return "XAUUSD"/);
  assert.match(localPatternsSource, /target === "GBPAUD" \|\| target === "GBPCAD" \|\| target === "GBPJPY"\) return "GBPUSD"/);
  assert.match(localPatternsSource, /target === "GBPUSD" \|\| target === "EURUSD" \|\| target === "GBPCAD"/);
  assert.match(localPatternsSource, /target === "GBPJPY" && slotHour === 3/);
  assert.match(scannerSource, /base === "GBPAUD" \|\| base === "GBPCAD" \|\| base === "GBPJPY"\) return "GBPAUD"/);
  assert.match(scannerSource, /if \(base === "GBPAUD"\) return "AUDUSD"/);
  assert.match(scannerSource, /if \(base === "GBPCAD"\) return "USDCAD"/);
  assert.match(scannerSource, /if \(base === "GBPJPY"\) return "USDJPY"/);
  assert.match(scannerSource, /baseSymbol: signalBaseSource/);
  assert.doesNotMatch(scannerSource, /pairReferenceSignal|gbpaudFinalSignalForSlot|localSignalInvertedForTarget/);
});

test("web tab softly refreshes server data every 20 seconds", () => {
  assert.match(layoutSource, /<TabAutoRefresh \/>/);
  assert.match(tabAutoRefreshSource, /TAB_AUTO_REFRESH_MS = 20_000/);
  assert.match(tabAutoRefreshSource, /window\.setInterval/);
  assert.match(tabAutoRefreshSource, /router\.refresh\(\)/);
  assert.match(tabAutoRefreshSource, /window\.clearInterval/);
  assert.doesNotMatch(tabAutoRefreshSource, /location\.reload/);
});

test("H16 copies H14 for XAU H3 entry H5 and inverts H14 with CLOSE only for H3 entry H4", () => {
  assert.match(boardSource, /function isManualCloseH16Day/);
  assert.match(boardSource, /slotHour === 3 && alert\.entryHour === 4/);
  assert.doesNotMatch(boardSource, /slotHour === 3 && alert\.entryHour === 5/);
  assert.match(nativeModelsSource, /\$0\.slotHour == 3 && \$0\.entryHour == 4/);
  assert.doesNotMatch(nativeModelsSource, /\$0\.slotHour == 3 && \$0\.entryHour == 5/);
  assert.match(androidModelsSource, /it\.slotHour == 3 && it\.entryHour == 4/);
  assert.doesNotMatch(androidModelsSource, /it\.slotHour == 3 && it\.entryHour == 5/);
  assert.match(boardSource, /oak-h1-close-badge/);
  assert.match(boardSource, /data-manual-close=\{hour === 16 && manualCloseH16/);
  assert.match(boardSource, /drawCentered\(alert\?\.signal \|\| "—"/);
  assert.match(boardSource, /<small data-signal=\{alert\?\.signal \|\| undefined\}>\{alert\?\.signal \|\| "—"\}<\/small>/);
  assert.doesNotMatch(boardSource, /manualCloseCell|data-action=/);
  assert.match(boardSource, /oak-h1-close-advisory/);
  assert.match(redesignCss, /\.oak-h1-close-badge/);
  assert.doesNotMatch(redesignCss, /tbody td\[data-manual-close="true"\]|data-action="CLOSE"/);
  assert.match(androidScreensSource, /if \(manualClose\) Text\("CLOSE", color = p\.warning/);
  assert.doesNotMatch(androidScreensSource, /manualClose -> OAKPill\("CLOSE", PillTone\.WARNING\)/);
  assert.match(androidScreensSource, /Fact\("BASE CANDLE", facts\.rawBase\)/);
  assert.match(androidScreensSource, /if \(facts\.signalSource\.isNotBlank\(\)\) Fact\("FINAL SOURCE", facts\.signalSource\)/);
  assert.match(androidScreensSource, /Fact\("RULE", facts\.rule\)/);
  assert.match(androidScreensSource, /Fact\("FINAL", facts\.finalSignal\)/);
  assert.match(androidModelsSource, /fun evidenceFacts\(date: String, sourceAlert: H1SignalAlert\): H1EvidenceFacts/);
  assert.match(androidModelsSource, /var signalSource = ""/);
  assert.match(androidModelsSource, /sourceAlert\.slotHour == 16/);
  assert.match(androidModelsSource, /sourceAlert\.symbol, 14/);
  assert.match(androidModelsSource, /xauH3Entry == 4 -> "INVERT H14"/);
  assert.match(androidModelsSource, /xauH3Entry == 5 -> "COPY H14"/);
  assert.match(androidShareSource, /val closeBadge = manualClose && hour == 16/);
  assert.match(androidShareSource, /when \(alert\?\.signal\)/);
  assert.match(nativeH1BoardSource, /OAKPill\(label: "CLOSE", tone: \.warning\)/);
  assert.doesNotMatch(nativeSignalsSource, /let close =|if close|manualClose && alert\.slotHour == 16/);
  assert.match(nativeEvidenceSource, /fact\("BASE CANDLE", facts\.rawBase\)/);
  assert.match(nativeEvidenceSource, /if !facts\.signalSource\.isEmpty \{ fact\("FINAL SOURCE", facts\.signalSource\) \}/);
  assert.match(nativeEvidenceSource, /fact\("RULE", facts\.rule\)/);
  assert.match(nativeEvidenceSource, /fact\("FINAL", facts\.finalSignal\)/);
  assert.match(nativeModelsSource, /func evidenceFacts\(date: String, sourceAlert: H1SignalAlert\) -> H1EvidenceFacts/);
  assert.match(nativeModelsSource, /var signalSource = ""/);
  assert.match(nativeModelsSource, /sourceAlert\.slotHour == 16/);
  assert.match(nativeModelsSource, /alert\(date: date, symbol: sourceAlert\.symbol, hour: 14\)/);
  assert.match(nativeModelsSource, /xauH3Entry == 4 \? "INVERT H14" : xauH3Entry == 5 \? "COPY H14"/);
  assert.doesNotMatch(nativeEvidenceSource, /"GBPUSD H\\\(alert\.baseHour/);
  assert.doesNotMatch(boardSource + androidScreensSource, /order_send|closePosition|dispatchTask|\/approve/);
});

test("GBPAUD, GBPCAD and GBPJPY are visible again across web iOS and Android", () => {
  assert.match(boardSource, /H1_TEMP_HIDDEN_ROWS = new Set<string>\(\)/);
  assert.match(boardSource, /visibleH1Symbols\(data\.symbols\)/);
  assert.match(boardSource, /visibleH1Symbols\(H1_TARGET_BASES\)/);
  assert.match(androidScreensSource, /VisibleSymbols = listOf\("XAUUSD", "GBPUSD", "EURUSD", "GBPAUD", "GBPCAD", "GBPJPY"\)/);
  assert.match(nativeH1BoardSource, /visibleSymbols = \["XAUUSD", "GBPUSD", "EURUSD", "GBPAUD", "GBPCAD", "GBPJPY"\]/);
  assert.match(scannerSource, /H1_TARGET_BASES = H1_LOCAL_TARGETS/);
});

test("H1 cells render entry hour plus final rule-derived BUY/SELL", () => {
  assert.match(boardSource, /oak-h1-cell-entry/);
  assert.match(boardSource, /alert\?\.entryHour/);
  assert.match(boardSource, /alert\?\.signal/);
  assert.match(boardSource, /data-signal=\{alert\?\.signal/);
  assert.match(boardSource, /data-pattern-group/);
  assert.match(boardSource, /scannerSource/);
  assert.doesNotMatch(boardSource, /data-scheduled-signal/);
  assert.doesNotMatch(boardSource, /data-post-signal-inverted/);
  assert.match(redesignCss, /\.oak-h1-cell-entry small\[data-signal="BUY"\]/);
  assert.match(redesignCss, /\.oak-h1-cell-entry small\[data-signal="SELL"\]/);
  assert.doesNotMatch(boardSource, /isEntryReferenceCell|data-entry-reference/);
  assert.doesNotMatch(redesignCss, /data-entry-reference/);
  assert.doesNotMatch(nativeH1BoardSource, /entryReference|isReference\(symbol:/);
  assert.doesNotMatch(androidScreensSource, /entryReference/);
  assert.doesNotMatch(androidShareSource, /val reference = \(symbol == "XAUUSD"/);
});

test("light theme keeps the H16 CLOSE badge and normal signal pills high-contrast", () => {
  assert.doesNotMatch(redesignCss, /data-entry-reference/);
  assert.match(redesignCss, /html\.light \.oak-h1-table thead th\[data-manual-close="true"\]/);
  assert.match(redesignCss, /html\.light \.oak-h1-close-badge/);
  assert.doesNotMatch(redesignCss, /tbody td\[data-manual-close="true"\]|data-action="CLOSE"/);
  assert.match(redesignCss, /html\.light \.oak-h1-cell-entry small\[data-signal="BUY"\]/);
  assert.match(redesignCss, /html\.light \.oak-h1-cell-entry small\[data-signal="SELL"\]/);
  assert.match(redesignCss, /border-width: 2px/);
});

test("native iOS polish keeps H1 matrix clean, image clipboard, sparse report dates, distinct contrast, and live account toggles", () => {
  const matrixCellStart = nativeH1BoardSource.indexOf("private struct H1MatrixCell");
  const matrixCellEnd = nativeH1BoardSource.indexOf("private struct BrokerCalendarSheet");
  const matrixCellSource = nativeH1BoardSource.slice(matrixCellStart, matrixCellEnd);
  assert.match(nativeH1BoardSource, /HStack\(alignment: \.top, spacing: 6\)/);
  assert.match(matrixCellSource, /RoundedRectangle\(cornerRadius: 11/);
  assert.doesNotMatch(matrixCellSource, /overlay\(alignment: \.trailing\)|overlay\(alignment: \.bottom\)|Divider\(\)/);

  assert.match(nativeEvidenceSource, /COPY CHART/);
  assert.match(nativeEvidenceSource, /SHARE CHART/);
  assert.match(nativeEvidenceSource, /M15 candlestick chart · oldest → newest/);
  assert.match(nativeEvidenceSource, /private var chronologicalBars:[\s\S]*bars\.sorted/);
  assert.match(androidScreensSource, /val safe = bars\.sortedWith/);
  assert.match(androidShareSource, /val bars = alert\.sampleBars\.sortedWith/);
  assert.match(nativeEvidenceSource, /ImageRenderer\(content: view\)/);
  assert.match(nativeEvidenceSource, /OAKImageTransfer\.copyPNG\(image\)/);
  assert.match(nativeImageTransferSource, /UIPasteboard\.general\.setItems/);
  assert.match(nativeImageTransferSource, /UTType\.png\.identifier/);
  assert.doesNotMatch(nativeEvidenceSource, /public\.svg-image|public\.utf8-plain-text|COPY CHART SVG|<svg/);

  assert.match(nativeReportsSource, /x: \.value\("Index", point\.index\)/);
  assert.match(nativeReportsSource, /AxisMarks\(values: visibleAxisIndices\(reports\.trend\)\)/);
  assert.match(nativeReportsSource, /font\(\.system\(size: 9, weight: \.bold, design: \.monospaced\)\)/);

  assert.match(nativeThemeSource, /case \.contrast: Color\(hex: contrast\)/);
  assert.match(nativeThemeSource, /contrast: 0x000000/);
  assert.match(nativeThemeSource, /contrast: 0xFFFFFF/);
  assert.match(nativeThemeSource, /contrast: 0x66A3FF/);
  assert.match(nativeAppSource, /\.id\(state\.themeMode\)/);

  assert.match(nativeAppStateSource, /applyAccountEnabledLocally\(id: id, enabled: enabled\)/);
  assert.match(nativeAppStateSource, /payload = previous/);
  assert.match(nativeAppStateSource, /Task \{ @MainActor \[weak self\] in/);
  assert.match(nativeMoreSource, /first\(where: \{ \$0\.id == account\.id \}\)\?\.enabled/);
  assert.match(nativeMoreSource, /© 2026 QuachGia/);
  assert.match(nativeMoreSource, /MIT License/);
  assert.match(licenseSource, /MIT License/);
  assert.match(licenseSource, /Copyright \(c\) 2026 QuachGia/);
});

test("mobile account status prefers sanitized local-primary MT5 heartbeat evidence over obsolete cloud bridge status", () => {
  assert.match(localPrimaryFenceSource, /accounts: LocalPrimaryMt5Heartbeat\[\]/);
  assert.match(localControllerSource, /function localPrimaryFenceAccounts/);
  assert.match(localControllerSource, /providerAccountId: String\(row\.providerAccountId/);
  assert.match(localControllerSource, /localReady: row\.localReady !== false/);
  assert.match(localControllerSource, /eaVersion: String\(row\.eaVersion/);
  assert.match(localControllerSource, /const webStatus = options\.webStatus/);
  assert.match(localControllerSource, /\/api\/telegram\/local-status/);
  assert.match(localStatusRouteSource, /x-telegram-bot-api-secret-token/);
  assert.match(localStatusRouteSource, /writeLocalPrimaryFence/);
  assert.match(localStatusRouteSource, /syncManagedMt5AccountsFromLocalHeartbeats/);
  assert.match(localStatusRouteSource, /enabled: row\.enabled !== false/);
  assert.match(localStatusRouteSource, /MAX_CLOCK_SKEW_MS/);
  assert.match(androidScreensSource, /© 2026 QuachGia/);
  assert.match(androidScreensSource, /local heartbeat online/);
  assert.match(androidScreensSource, /Local heartbeat pending/);
  assert.match(androidManifestSource, /android:icon="@mipmap\/ic_launcher"/);
  const androidAdaptiveIconSource = readFileSync(new URL("../../../android-native/app/src/main/res/mipmap-anydpi/ic_launcher.xml", import.meta.url), "utf8");
  assert.match(androidAdaptiveIconSource, /@color\/oak_launcher_mask_bg/);
  assert.match(androidAdaptiveIconSource, /@drawable\/oak_launcher_foreground/);
  assert.doesNotMatch(androidAdaptiveIconSource, /oak_launcher_foreground_inset/);
  assert.match(androidAdaptiveIconSource, /@drawable\/oak_launcher_monochrome/);
  assert.match(androidLauncherColorsSource, /<color name="oak_launcher_mask_bg">#08111F<\/color>/);
  const nativeProjectSource = readFileSync(new URL("../../../ios-native/project.yml", import.meta.url), "utf8");
  const nativeAppIconCatalogSource = readFileSync(new URL("../../../ios-native/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json", import.meta.url), "utf8");
  assert.match(nativeProjectSource, /ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon/);
  assert.match(nativeProjectSource, /path: Resources[\s\S]*buildPhase: resources/);
  assert.match(nativeAppIconCatalogSource, /"filename" : "AppIcon\.png"/);
  assert.match(nativeAppIconCatalogSource, /"size" : "1024x1024"/);
  assert.match(providerAccountStatusSource, /readLocalPrimaryFence/);
  assert.match(providerAccountStatusSource, /bridgeRuntime: "local-primary"/);
  assert.match(providerAccountStatusSource, /local-primary-offline/);
  assert.match(providerAccountStatusSource, /Boolean\(account\.bridgeProfile\) && sameText\(row\.profile, account\.bridgeProfile\)/);
  assert.match(providerAccountStatusSource, /const bridgeRuntime: "local-primary-offline" \| "local-primary-pending"/);
  assert.match(providerAccountStatusSource, /getMt5BridgeHeartbeat/);
  assert.match(mobileAppBackendSource, /providerAccountsWithRuntimeStatus\(accounts\)/);
  assert.match(nativeMoreSource, /Local heartbeat online/);
  assert.match(nativeMoreSource, /Local heartbeat offline/);
  assert.match(androidScreensSource, /Local heartbeat offline/);
  assert.doesNotMatch(nativeMoreSource, /Bridge offline|bridge online/);
});

test("H1 table sizes itself from the active columns and stretches across desktop viewports", () => {
  assert.match(redesignCss, /\.oak-engine-screen \{[^}]*width: 100%;/);
  assert.match(redesignCss, /\.oak-h1-table \{[^}]*width: max-content;[^}]*min-width: 100%;/);
  assert.match(redesignCss, /\.oak-h1-table th, \.oak-h1-table td \{[^}]*min-width: 4\.45rem;/);
  assert.match(redesignCss, /@media \(min-width: 900px\) \{[\s\S]*?\.oak-h1-table \{ width: 100%; min-width: 100%; \}[\s\S]*?\.oak-h1-table th, \.oak-h1-table td \{ width: auto; min-width: 0; \}/);
  assert.match(redesignCss, /\.oak-h1-symbol-sticky \{ width: clamp\(8rem, 10vw, 11rem\) !important;/);
  assert.doesNotMatch(redesignCss, /\.oak-engine-screen \{[^}]*1080px/);
  assert.doesNotMatch(redesignCss, /\.oak-h1-table \{[^}]*min-width: 79rem;/);
});

test("H1 board omits the separate Entry Focus panel", () => {
  assert.doesNotMatch(boardSource, /H1EntryFocus|oak-entry-focus/);
  assert.match(boardSource, /oak-h1-history/);
  assert.match(boardSource, /oak-h1-table/);
  assert.doesNotMatch(redesignCss, /\.oak-entry-focus/);
});

test("H1 Live and History temporarily expose every entry cell as free access", () => {
  assert.match(vipSource, /VIP_FREE_ACCESS = true/);
  assert.match(engineBoardSource, /FREE ACCESS/);
  assert.match(engineBoardSource, /All H1 entry-time cells unlocked/);
  assert.match(boardSource, /oak-h1-free-access/);
  assert.doesNotMatch(boardSource, /VIP_SIGNAL_SYMBOL|oak-h1-cell-locked|VIP required/);
  assert.doesNotMatch(engineBoardSource, /VIP UNLOCK|VIP LOCKED|\/api\/vip|useDialogFocusTrap/);
  assert.doesNotMatch(enginePageSource, /redactH1Signals|getVipAccessState/);
  assert.doesNotMatch(historyPageSource, /redactH1Signals|getVipAccessState/);
});

test("H1 history uses a deterministic Sunday-first calendar without weekday filter controls", () => {
  assert.match(boardSource, /function SundayCalendarPicker/);
  assert.match(boardSource, /\[\"CN\", \"T2\", \"T3\", \"T4\", \"T5\", \"T6\", \"T7\"\]/);
  assert.match(boardSource, /getUTCDay\(\)/);
  assert.match(boardSource, /sundayOffset/);
  assert.match(boardSource, /allowedDates=\{allDates\}/);
  assert.match(boardSource, /disabled=\{!allDates\.length\}/);
  assert.match(boardSource, /data-empty=\"true\"/);
  assert.match(boardSource, /fallbackMinDate/);
  assert.match(boardSource, /calendar dự phòng/);
  assert.doesNotMatch(boardSource, /type=\"date\"/);
  assert.doesNotMatch(boardSource, /HISTORY_FILTERS|weekdayFilter|oak-h1-history-options|Lọc theo thứ|Filter by weekday/);
  assert.match(redesignCss, /\.oak-h1-calendar-picker \{/);
  assert.match(redesignCss, /\.oak-h1-calendar-weekdays/);
  assert.match(redesignCss, /grid-template-columns: repeat\(7, 1\.75rem\)/);
  assert.match(redesignCss, /width: min\(15rem, calc\(100vw - 1\.25rem\)\)/);
  assert.match(redesignCss, /\.oak-h1-board \{[\s\S]*?overflow: visible;/);
  assert.match(redesignCss, /\.oak-h1-history \{[^}]*z-index: 30;[^}]*overflow: visible;/);
  assert.match(redesignCss, /\.oak-h1-table-scroll \{[^}]*overflow-y: hidden;[^}]*border-radius:/);
  assert.doesNotMatch(redesignCss, /\.oak-h1-board \{[^}]*overflow: hidden;/);
  assert.doesNotMatch(redesignCss, /width: min\(20\.5rem/);
  assert.doesNotMatch(boardSource, /oak-h1-history-dates/);
});

test("legacy weekday and CẦU presentation stays hidden from H1 cells", () => {
  assert.doesNotMatch(boardSource, /inversionBadge|data-post-signal-inverted|INVERT|ĐẢO/);
  assert.doesNotMatch(boardSource, /isMonthEndBridgeCell|oak-h1-bridge-badge|data-month-end-bridge|CẦU/);
  assert.doesNotMatch(evidencePanelSource, /Weekday:|WEEKDAY|ĐẢO|GIỮ/);
  assert.match(evidencePanelSource, /SIGNAL/);
  assert.match(evidencePanelSource, /Base:/);
});

test("mobile H1 adapter preserves admin auth and normalized cloud feed semantics", () => {
  assert.match(mobileH1RouteSource, /requireAdminOrApiAuth/);
  assert.match(mobileH1RouteSource, /getLatestH1Signals/);
  assert.match(mobileH1RouteSource, /maskFutureH1Signals/);
  assert.match(mobileH1RouteSource, /Cache-Control.*no-store/);
  assert.doesNotMatch(mobileH1RouteSource, /UPSTASH|CTRADER_CLIENT_SECRET|DASHBOARD_API_KEY/);
});

test("mobile app backend exposes one authenticated app payload without leaking secrets", () => {
  assert.match(mobileAppRouteSource, /requireAdminOrApiAuth/);
  assert.match(mobileAppRouteSource, /buildMobileAppPayload/);
  assert.match(mobileAppRouteSource, /Cache-Control.*no-store/);
  assert.match(mobileAppBackendSource, /dashboardSummary/);
  assert.match(mobileAppBackendSource, /reportSummary/);
  assert.match(mobileAppBackendSource, /bridgeSummary/);
  assert.match(mobileAppBackendSource, /systemSummary/);
  assert.match(mobileAppBackendSource, /payloadVersion: 2/);
  assert.match(mobileAppBackendSource, /isMonthEndBridgeCell/);
  assert.doesNotMatch(mobileAppRouteSource + mobileAppBackendSource, /CTRADER_CLIENT_SECRET|DASHBOARD_API_KEY|UPSTASH_REDIS_REST_TOKEN/);
});

test("native Android mirrors the iOS five-tab hierarchy and removes the legacy Dashboard/VIP surface", () => {
  assert.match(androidMainSource, /OAKTab\.LIVE/);
  assert.match(androidMainSource, /OAKTab\.HISTORY/);
  assert.match(androidMainSource, /OAKTab\.SIGNALS/);
  assert.match(androidMainSource, /OAKTab\.REPORTS/);
  assert.match(androidMainSource, /OAKTab\.MORE/);
  assert.match(androidMainSource, /NavigationBarItem/);
  assert.match(androidScreensSource, /TRADING \/ H1 LIVE/);
  assert.match(androidScreensSource, /TRADING \/ HISTORY/);
  assert.match(androidScreensSource, /TRADING \/ SIGNALS/);
  assert.match(androidScreensSource, /TRADING \/ REPORTS/);
  assert.match(androidScreensSource, /OAK \/ SYSTEM/);
  assert.doesNotMatch(androidScreensSource + androidMainSource, /VIP UNLOCKED|HỆ THỐNG ONLINE|DashboardScreen|OAK SLTP/);
});

test("native Android copies the iOS H1 presentation, evidence, reports, themes and account interaction", () => {
  assert.match(androidScreensSource, /VisibleSymbols = listOf\("XAUUSD", "GBPUSD", "EURUSD", "GBPAUD", "GBPCAD", "GBPJPY"\)/);
  assert.doesNotMatch(androidScreensSource, /entryReference/);
  assert.match(androidScreensSource, /OAKPill\("FREE ACCESS", PillTone\.SUCCESS\)/);
  assert.match(androidScreensSource, /BrokerCalendarSheet/);
  assert.match(androidScreensSource, /listOf\("CN", "T2", "T3", "T4", "T5", "T6", "T7"\)/);
  assert.match(androidScreensSource, /List\(42\)/);
  assert.match(androidScreensSource, /monthAnchor\.minusMonths\(1\)/);
  assert.match(androidScreensSource, /monthAnchor\.plusMonths\(1\)/);
  assert.match(androidScreensSource, /Icons\.Default\.DateRange/);
  assert.match(androidScreensSource, /COPY PNG/);
  assert.match(androidScreensSource, /SHARE PNG/);
  assert.match(androidScreensSource, /COPY CHART/);
  assert.match(androidScreensSource, /SHARE CHART/);
  assert.match(androidShareSource, /copyScheduleToClipboard/);
  assert.match(androidShareSource, /Intent\.ACTION_SEND/);
  assert.match(androidShareSource, /Intent\.EXTRA_STREAM/);
  assert.match(androidShareSource, /Intent\.FLAG_GRANT_READ_URI_PERMISSION/);
  assert.match(androidShareSource, /Intent\.createChooser/);
  assert.match(androidShareSource, /ClipData\.newUri/);
  assert.match(androidShareSource, /createBitmap\(Width, Height/);
  assert.match(androidShareSource, /bitmap\.recycle\(\)/);
  assert.match(androidScreensSource, /bar\.brokerTime/);
  assert.match(androidScreensSource, /index == 0 \|\| index == trend\.lastIndex \|\| index % 2 == 0/);
  assert.match(androidThemeSource, /canvas = Color\.Black/);
  assert.match(androidThemeSource, /text = Color\.White/);
  assert.match(androidStateSource, /applyAccountEnabledLocally\(id, enabled\)/);
  assert.match(androidStateSource, /payload = previous/);
  assert.match(androidStateSource, /fun unlock\(candidate: String\)/);
  assert.match(androidStateSource, /viewModelScope\.launch/);
  assert.match(androidStateSource, /val initialPayload = api\.fetchApp\(key\)/);
  assert.doesNotMatch(androidScreensSource, /rememberCoroutineScope/);
  assert.doesNotMatch(androidStateSource, /refresh\(forceLoading = true\)/);
  assert.match(androidScreensSource, /Switch\(checked = account\.enabled/);
  assert.match(androidScreensSource, /© 2026 QuachGia/);
  assert.match(androidScreensSource, /MIT License/);
  assert.match(androidMainSource, /R\.drawable\.ic_tab_live/);
  assert.match(androidMainSource, /R\.drawable\.ic_tab_history/);
  assert.match(androidMainSource, /R\.drawable\.ic_tab_signals/);
  assert.match(androidMainSource, /R\.drawable\.ic_tab_reports/);
  assert.match(androidMainSource, /R\.drawable\.ic_tab_more/);
});

test("native Android is hardened for Google Play February 2027 memory and DEX requirements", () => {
  assert.match(androidBuildSource, /compileSdk = 36/);
  assert.match(androidBuildSource, /targetSdk = 36/);
  assert.match(androidBuildSource, /isMinifyEnabled = true/);
  assert.match(androidBuildSource, /isShrinkResources = true/);
  assert.match(androidBuildSource, /warningsAsErrors = true/);
  assert.match(androidBuildSource, /"OldTargetApi", "AndroidGradlePluginVersion", "GradleDependency"/);
  assert.match(androidBuildSource, /jniLibs\.useLegacyPackaging = false/);
  assert.match(androidGradlePropertiesSource, /android\.enableR8\.fullMode=true/);
  assert.match(androidMainSource, /onTrimMemory/);
  assert.match(androidMainSource, /TRIM_MEMORY_UI_HIDDEN/);
  assert.match(androidMainSource, /onLowMemory/);
  assert.match(androidShareSource, /trimTransient/);
  assert.match(androidShareSource, /ExportRetentionMs/);
  assert.match(androidShareSource, /ClipboardSafetyWindowMs/);
  assert.match(androidShareSource, /pruneExports\(context\)/);
  assert.doesNotMatch(androidShareSource, /listFiles\(\)\?\.forEach \{ it\.delete\(\) \}/);
  assert.doesNotMatch(androidScreensSource + androidStateSource, /Coil|Glide|BitmapFactory|staticBitmap|imageCache/i);
  assert.match(androidManifestSource, /android:allowBackup="false"/);
  assert.match(androidManifestSource, /android:fullBackupContent="false"/);
  assert.match(androidManifestSource, /android:dataExtractionRules="@xml\/data_extraction_rules"/);
  assert.match(androidManifestSource, /Theme\.OAKGatekeeper\.Splash/);
  assert.match(androidStylesSource, /parent="Theme\.SplashScreen"/);
  assert.match(androidStylesSource, /windowSplashScreenAnimatedIcon/);
  assert.match(androidMainSource, /installSplashScreen\(\)/);
  assert.match(androidMainSource, /OAKLaunchLoading/);
  assert.match(androidMainSource, /R\.drawable\.oak_app_icon_exact/);
  assert.match(nativeAppSource, /OAKLaunchLoadingView/);
  assert.match(nativeAppSource, /Image\("OAKLogo"\)/);
  assert.match(webLoadingSource, /oak-app-icon\.png/);
  assert.match(webLoadingSource, /oak-loading-spinner/);
  assert.match(brandSyncSource, /AppIcon\.appiconset/);
  assert.match(brandSyncSource, /oak_app_icon_exact\.png/);
  assert.match(brandSyncSource, /oak_launcher_foreground\.png/);
  assert.match(brandSyncSource, /generated transparent adaptive foreground/);
  assert.match(brandSyncSource, /oak-app-icon\.png/);
  assert.doesNotMatch(androidManifestSource, /android:screenOrientation="portrait"/);
});

test("engine web surface is local-H1-only with the compact command header", () => {
  assert.doesNotMatch(enginePageSource, /getLatestPattern5|filterActivePattern5|maskFuturePattern5|redactPattern5Signals/);
  assert.doesNotMatch(engineBoardSource, /Pattern5Payload|Pattern5Table|ENGINE 05|Pattern Matrix|Trạng thái tín hiệu hiện tại|<small>PROFILE<\/small>|h1Data\?\.profile/);
  assert.match(engineBoardSource, /TRADING \/ H1 LOCAL/);
  assert.match(engineBoardSource, /MT5 ICMarkets · M15/);
  assert.doesNotMatch(engineBoardSource, /UNLOCK SIGNALS/);
});

test("H1 board exports interoperable PNG clipboard data and native share fallbacks", () => {
  assert.match(boardSource, /oak-h1-share-png/);
  assert.match(boardSource, /document\.createElement\("canvas"\)/);
  assert.match(boardSource, /canvas\.toBlob/);
  assert.match(boardSource, /H1_SHARE_SCALE = 2/);
  assert.match(boardSource, /navigator\.clipboard\?\.write/);
  assert.match(boardSource, /new ClipboardItem\(\{ "image\/png": shareArtifact\.blob \}\)/);
  assert.doesNotMatch(boardSource, /navigator\.share\(|navigator\.canShare|anchor\.download|downloadPng/);
  assert.match(nativeH1BoardSource, /copySchedulePNG/);
  assert.match(nativeH1BoardSource, /shareSchedulePNG/);
  assert.match(nativeH1BoardSource, /private struct ScheduleExportMatrix/);
  assert.match(nativeH1BoardSource, /ScheduleExportMatrix\(h1: h1, date: date, symbols: symbols\)/);
  assert.match(nativeH1BoardSource, /ForEach\(h1\.hours, id: \\.self\)/);
  assert.match(nativeH1BoardSource, /h1\.alert\(date: date, symbol: symbol, hour: hour\)/);
  const nativeExportStart = nativeH1BoardSource.indexOf("private struct ScheduleExportView");
  const nativeExportSource = nativeH1BoardSource.slice(nativeExportStart);
  assert.doesNotMatch(nativeExportSource, /H1MatrixView\(/);
  assert.doesNotMatch(nativeExportSource, /ScrollView\(\.horizontal/);
  assert.match(androidShareSource, /val hours = h1\.hours/);
  assert.match(androidShareSource, /val alert = h1\.alert\(brokerDate, symbol, hour\)/);
  assert.match(nativeH1BoardSource, /OAKImageTransfer\.copyPNG\(image\)/);
  assert.match(nativeH1BoardSource, /OAKImageTransfer\.exportPNG/);
  assert.match(nativeH1BoardSource, /SHARE PNG/);
  assert.match(nativeImageTransferSource, /UTType\.png\.identifier/);
  assert.match(nativeImageTransferSource, /UIPasteboard\.general\.setItems/);
  assert.match(nativeImageTransferSource, /\.localOnly: false/);
  assert.match(nativeImageTransferSource, /UIActivityViewController/);
  assert.match(nativeImageTransferSource, /retentionSeconds/);
  assert.match(nativeEvidenceSource, /SHARE CHART/);
  assert.match(nativeEvidenceSource, /OAKImageTransfer\.copyPNG\(image\)/);
  assert.match(androidShareSource, /copyScheduleToClipboard/);
  assert.match(androidShareSource, /shareSchedule/);
  assert.match(androidShareSource, /shareChart/);
  assert.match(androidShareSource, /clipboard\.setPrimaryClip\(clip\)/);
  assert.match(androidShareSource, /type = "image\/png"/);
  assert.match(androidScreensSource, /Đã copy PNG · có thể dán sang Telegram/);
  assert.match(boardSource, /activeH1ScanHoursForBrokerDate\(date, data\.hours\)/);
  assert.match(boardSource, /hours\.forEach/);
  assert.match(boardSource, /visibleSymbols\.forEach/);
  assert.match(redesignCss, /\.oak-h1-share-png \{/);
  assert.match(redesignCss, /data-copied="true"/);
});

test("populated H1 cells open deterministic M15 pattern evidence without cluttering the cell", () => {
  assert.match(boardSource, /oak-h1-cell-entry oak-h1-cell-evidence/);
  assert.match(boardSource, /setEvidenceSelection/);
  assert.match(boardSource, /<H1EvidencePanel selection=\{evidenceSelection\} payload=\{data\}/);
  assert.match(evidencePanelSource, /function evidenceFacts\(/);
  assert.match(evidencePanelSource, /let signalSource = ""/);
  assert.match(evidencePanelSource, /BASE CANDLE/);
  assert.match(evidencePanelSource, /FINAL SOURCE/);
  assert.match(evidencePanelSource, /facts\.signalSource &&/);
  assert.match(evidencePanelSource, /RULE/);
  assert.match(evidencePanelSource, /FINAL/);
  assert.match(evidencePanelSource, /COPY H14|INVERT H14/);
  assert.match(evidencePanelSource, /SYNC XAUUSD/);
  assert.match(evidencePanelSource, /M15 candlestick pattern evidence/);
  assert.match(evidencePanelSource, /sampleBars/);
  assert.match(evidencePanelSource, /Pattern Evidence · newest → oldest/);
  assert.match(evidencePanelSource, /navigator\.clipboard\.writeText/);
  assert.match(evidencePanelSource, /BLOCK H/);
  assert.match(evidencePanelSource, /ENTRY H/);
  assert.match(evidencePanelSource, /familyLabel/);
  assert.match(evidencePanelSource, /GT\/TG/);
  assert.match(evidencePanelSource, /TT\/GG/);
  assert.match(redesignCss, /\.oak-h1-evidence-panel/);
  assert.match(redesignCss, /\.oak-h1-evidence-chart/);
  assert.match(redesignCss, /@media \(max-width: 759px\)[\s\S]*\.oak-h1-evidence-backdrop \{ align-items: flex-end;/);
  assert.match(boardSource, /oak-h1-degraded/);
  assert.match(boardSource, /H1_SCAN_HOURS/);
  assert.match(boardSource, /H1_TARGET_BASES/);
});
