/**
 * Dictionary mapping Vietnam Stock Tickers to full Company Names across HOSE, HNX, UPCoM.
 */
export const COMPANY_NAMES: Record<string, { name: string; exchange: string }> = {
  // HOSE VN30 & Midcaps
  ACB: { name: "Ngân hàng Á Châu", exchange: "HOSE" },
  BCM: { name: "Tổng Công ty Becamex IDC", exchange: "HOSE" },
  BID: { name: "Ngân hàng BIDV", exchange: "HOSE" },
  BVH: { name: "Tập đoàn Bảo Việt", exchange: "HOSE" },
  CTG: { name: "Ngân hàng VietinBank", exchange: "HOSE" },
  FPT: { name: "Tập đoàn FPT", exchange: "HOSE" },
  GAS: { name: "Tổng Công ty Khí Việt Nam (PV GAS)", exchange: "HOSE" },
  GVR: { name: "Tập đoàn CN Cao su Việt Nam", exchange: "HOSE" },
  HDB: { name: "Ngân hàng HDBank", exchange: "HOSE" },
  HPG: { name: "Tập đoàn Hòa Phát", exchange: "HOSE" },
  MBB: { name: "Ngân hàng Quân Đội (MB)", exchange: "HOSE" },
  MSN: { name: "Tập đoàn Masan", exchange: "HOSE" },
  MWG: { name: "Công ty CP Thế Giới Di Động", exchange: "HOSE" },
  PLX: { name: "Tập đoàn Xăng dầu Việt Nam (Petrolimex)", exchange: "HOSE" },
  POW: { name: "Tổng Công ty Điện lực Dầu khí Việt Nam", exchange: "HOSE" },
  SAB: { name: "Tổng Công ty Sabeco", exchange: "HOSE" },
  SHB: { name: "Ngân hàng SHB", exchange: "HOSE" },
  SSB: { name: "Ngân hàng SeABank", exchange: "HOSE" },
  SSI: { name: "Công ty CP Chứng khoán SSI", exchange: "HOSE" },
  STB: { name: "Ngân hàng Sacombank", exchange: "HOSE" },
  TCB: { name: "Ngân hàng Techcombank", exchange: "HOSE" },
  TPB: { name: "Ngân hàng TPBank", exchange: "HOSE" },
  VCB: { name: "Ngân hàng Vietcombank", exchange: "HOSE" },
  VHM: { name: "Công ty CP Vinhomes", exchange: "HOSE" },
  VIB: { name: "Ngân hàng VIB", exchange: "HOSE" },
  VIC: { name: "Tập đoàn Vingroup", exchange: "HOSE" },
  VJC: { name: "Công ty CP Hàng không Vietjet", exchange: "HOSE" },
  VNM: { name: "Công ty CP Sữa Việt Nam (Vinamilk)", exchange: "HOSE" },
  VPB: { name: "Ngân hàng VPBank", exchange: "HOSE" },
  VRE: { name: "Công ty CP Vincom Retail", exchange: "HOSE" },
  DGC: { name: "Tập đoàn Hóa chất Đức Giang", exchange: "HOSE" },
  DCM: { name: "Phân bón Dầu khí Cà Mau", exchange: "HOSE" },
  DPM: { name: "Tổng Công ty Phân bón & Hóa chất Dầu khí", exchange: "HOSE" },
  DIG: { name: "Tổng Công ty DIC Corp", exchange: "HOSE" },
  DXG: { name: "Tập đoàn Đất Xanh", exchange: "HOSE" },
  FRT: { name: "Công ty CP Bán lẻ Kỹ thuật số FPT", exchange: "HOSE" },
  GEX: { name: "Tập đoàn GELEX", exchange: "HOSE" },
  HCM: { name: "Chứng khoán TP.HCM (HSC)", exchange: "HOSE" },
  KBC: { name: "Tổng Công ty Phát triển Đô thị Kinh Bắc", exchange: "HOSE" },
  KDH: { name: "Công ty CP Đầu tư & KD Nhà Khang Điền", exchange: "HOSE" },
  LPB: { name: "Ngân hàng Lộc Phát Việt Nam (LPBank)", exchange: "HOSE" },
  NLG: { name: "Công ty CP Đầu tư Nam Long", exchange: "HOSE" },
  NVL: { name: "Tập đoàn Đầu tư Địa ốc No Va (Novaland)", exchange: "HOSE" },
  PC1: { name: "Tập đoàn PC1", exchange: "HOSE" },
  PDR: { name: "Công ty CP Phát triển BĐS Phát Đạt", exchange: "HOSE" },
  PNJ: { name: "Công ty CP Vàng bạc Đá quý Phú Nhuận", exchange: "HOSE" },
  PVD: { name: "Tổng Công ty Khoan Dầu khí (PV Drilling)", exchange: "HOSE" },
  PVT: { name: "Tổng Công ty Vận tải Dầu khí (PVTrans)", exchange: "HOSE" },
  REE: { name: "Công ty CP Cơ Điện Lạnh", exchange: "HOSE" },
  SBT: { name: "Công ty CP Thành Thành Công - Biên Hòa", exchange: "HOSE" },
  VCI: { name: "Công ty CP Chứng khoán Vietcap", exchange: "HOSE" },
  VCS: { name: "Công ty CP Vicostone", exchange: "HOSE" },
  VGC: { name: "Tổng Công ty Viglacera", exchange: "HOSE" },
  VHC: { name: "Công ty CP Vĩnh Hoàn", exchange: "HOSE" },
  VND: { name: "Công ty CP Chứng khoán VNDIRECT", exchange: "HOSE" },
  VIX: { name: "Công ty CP Chứng khoán VIX", exchange: "HOSE" },
  EIB: { name: "Ngân hàng Eximbank", exchange: "HOSE" },
  EVF: { name: "Công ty CP Tài chính Điện lực", exchange: "HOSE" },
  ORS: { name: "Công ty CP Chứng khoán Tiên Phong", exchange: "HOSE" },
  CTS: { name: "Công ty CP Chứng khoán VietinBank", exchange: "HOSE" },
  FTS: { name: "Công ty CP Chứng khoán FPT", exchange: "HOSE" },
  AGR: { name: "Công ty CP Chứng khoán Agribank", exchange: "HOSE" },
  VCG: { name: "Tổng Công ty Vinaconex", exchange: "HOSE" },
  TCH: { name: "Công ty CP Đầu tư Dịch vụ Tài chính Hoàng Huy", exchange: "HOSE" },
  GMD: { name: "Công ty CP Gemadept", exchange: "HOSE" },
  HAH: { name: "Công ty CP Vận tải & Cảng biển Hải An", exchange: "HOSE" },
  HAG: { name: "Công ty CP Hoàng Anh Gia Lai", exchange: "HOSE" },
  HNG: { name: "Công ty CP Nông nghiệp Quốc tế HAGL", exchange: "HOSE" },
  VSC: { name: "Công ty CP Container Việt Nam (Viconship)", exchange: "HOSE" },
  ANV: { name: "Công ty CP Nam Việt (Navico)", exchange: "HOSE" },
  IDI: { name: "Công ty CP Đầu tư & Phát triển Đa Quốc Gia", exchange: "HOSE" },
  FMC: { name: "Công ty CP Thực phẩm Sao Ta", exchange: "HOSE" },
  PAN: { name: "Tập đoàn PAN", exchange: "HOSE" },

  // HNX
  BSI: { name: "Công ty CP Chứng khoán BIDC (BSC)", exchange: "HNX" },
  CEO: { name: "Tập đoàn C.E.O", exchange: "HNX" },
  IDC: { name: "Tổng Công ty IDICO", exchange: "HNX" },
  MBS: { name: "Công ty CP Chứng khoán MB", exchange: "HNX" },
  NTP: { name: "Công ty CP Nhựa Thiếu niên Tiền Phong", exchange: "HNX" },
  PVC: { name: "Tổng Công ty Hóa chất & Dịch vụ Dầu khí", exchange: "HNX" },
  PVS: { name: "Tổng Công ty Dịch vụ Kỹ thuật Dầu khí", exchange: "HNX" },
  SHS: { name: "Công ty CP Chứng khoán Sài Gòn - Hà Nội", exchange: "HNX" },
  TNG: { name: "Công ty CP Đầu tư & Thương mại TNG", exchange: "HNX" },
  VGS: { name: "Công ty CP Thép Việt Đức", exchange: "HNX" },
  HUT: { name: "Công ty CP Tasco", exchange: "HNX" },

  // UPCoM
  ACV: { name: "Tổng Công ty Cảng Hàng không Việt Nam", exchange: "UPCOM" },
  BSR: { name: "Công ty CP Lọc hóa dầu Bình Sơn", exchange: "UPCOM" },
  C4G: { name: "Tập đoàn CIENCO4", exchange: "UPCOM" },
  DDV: { name: "Công ty CP DAP - VINACHEM", exchange: "UPCOM" },
  MCH: { name: "Công ty CP Hàng tiêu dùng Masan", exchange: "UPCOM" },
  MSR: { name: "Công ty CP Masan High-Tech Materials", exchange: "UPCOM" },
  OIL: { name: "Tổng Công ty Dầu Việt Nam (PVOIL)", exchange: "UPCOM" },
  QNS: { name: "Công ty CP Đường Quảng Ngãi", exchange: "UPCOM" },
  VEA: { name: "Tổng Công ty Máy động lực & Máy nông nghiệp", exchange: "UPCOM" },
  VGT: { name: "Tập đoàn Dệt May Việt Nam (Vinatex)", exchange: "UPCOM" },
};

export function getCompanyName(symbol: string): string {
  const sym = (symbol || "").toUpperCase().trim();
  if (!sym) return "";
  return COMPANY_NAMES[sym]?.name || `Công ty CP ${sym}`;
}
